version: '3'

networks:
  nginx:
    name: nginx
    driver: bridge

services:
  # docker 管理WebUI
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer/data:/data # host:docker
    ports:
      - 3089:9000
    networks:
      nginx:
        aliases:
          - portainer

  # nginx 扩展分支
  openresty:
    image: openresty/openresty:buster
    container_name: openresty
    restart: always
    user: root
    environment:
      - TZ="Asia/Shanghai"
    volumes:
      - ./nginx/config/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - ./nginx/cert:/usr/local/openresty/nginx/conf/cert:ro
      - ./nginx/log:/usr/local/openresty/nginx/logs
      - /etc/localtime:/etc/localtime
    ports:
      - 80:80
      - 443:443
    networks:
      nginx:
        aliases:
          - nginx

  # mssql:
  #   image: mcr.microsoft.com/mssql/server:2019-latest
  #   container_name: mssql
  #   restart: unless-stopped
  #   user: root
  #   environment:
  #     ACCEPT_EULA: Y
  #     MSSQL_SA_PASSWORD: MentalIsland.2022
  #     # MSSQL_SA_PASSWORD: /run/secrets/mysql_root_password #Sikro.1993
  #     MSSQL_PID: Express
  #   volumes:
  #     - ./mssql/data:/var/opt/mssql/data
  #     - ./mssql/log:/var/opt/mssql/log
  #     - ./mssql/backup:/var/opt/backup
  #   ports:
  #     - 1433:1433
  #   networks:
  #     nginx:
  #       aliases:
  #         - mssql

  # 心理岛网站后端+后台
  MentalIsland:
    build:
      context: .
      dockerfile: Dockerfile
    image: yxx/mentalisland:latest
    container_name: MentalIsland
    restart: always
    ports:
      - 5775:5775
    volumes:
      - ./MentalIsland.Web/wwwroot/images:/MentalIsland/wwwroot/images
      - ./MentalIsland.Web/wwwroot/Upload:/MentalIsland/wwwroot/Upload
      - ./database/MentalIsland.db:/MentalIsland/MentalIsland.db:rw
    # depends_on:
    #   - mssql
    networks:
      nginx:
        aliases:
          - MentalIsland

  # 心理岛网站前端
  lidao:
    build:
      context: .
      dockerfile: Lidao.Dockerfile
    image: yxx/lidao:latest
    container_name: lidao
    restart: always
    ports:
      - 8000:8000
    networks:
      nginx:
        aliases:
          - lidao

  # 心理岛网站前端(新版)
  lidaonew:
    build:
      context: .
      dockerfile: Lidao2.Dockerfile
    image: yxx/lidaonew:latest
    container_name: lidaonew
    restart: always
    ports:
      - 8100:8100
    networks:
      nginx:
        aliases:
          - lidaonew
